### ISSUE TITLE
Maxamount is not defined until instantiated in a tank

### ISSUE THREAD

**Issue by westlakem** [KSP-RO/RealFuels#319]
![image](https://github.com/KSP-RO/RP-1/assets/4505074/4e5db42b-dd98-4a16-a541-0d9f3fd63b24)

This often happens to me when trying to re-size Avionics, and doesn't allow me to resize them

**Comment by siimav** [comment]
Fixed by 0776e6a7642c128a86b96fe54baf708172606490
