### ISSUE TITLE
NaN when thrust is rounded below 0.1 N

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RealFuels#320]
If an engine has a thrust below 0.05 N, such that the display value is rounded down, the thrust is simply set to NaN and the engine does not work. RF seems to have no issue displaying smaller values (an engine with a thrust of 0.1 N will happily display throttled thrust in milli- or micro-Newtons), the issue only occurs if the config thrust is set too low.

This effects a lot of ion engines, since most of them have very low thrust values.

**Comment by Capkirk123** [comment]
Upon some investigation (by siimav), it seems like a potential cause is an incorrectly set up if else at https://github.com/KSP-RO/RealFuels/blob/f2b440d5731c4a804f6c832cbd933e6227a2d625/Source/Utilities/Utilities.cs#L189

**Comment by siimav** [comment]
That shouldn't actually be an issue. I get extra jumpy when someone writes inconsistent `if`s and `else if`s after one another. It's a definite code smell but doesn't actually matter since there's a `return`.
