### ISSUE TITLE
3-way mod interaction that leads to infinite NREs

### ISSUE THREAD

**Issue by SpacedInvader** [KSP-RO/RealFuels#328]
Was suggested I share this here since the RF team doesn't seem very active on the thread these days and I guess the RO discord is the wrong place for this. The forum post details the specifics, but basically, I've identified a 3-way interaction between Real Fuels, Rover Science, and Extended Information About Scientific Experiments that leads to RF producing an infinite loop of NREs. I've also notified LGG because both of the other mods are his, but since the NRE is RF, he's hoping to hear from the RF team first.

https://forum.kerbalspaceprogram.com/topic/58236-18-real-fuels/?do=findComment&comment=4306857

**Comment by NathanKell** [comment]
Try this dll please: https://github.com/KSP-RO/RealFuels/suites/14746267519/artifacts/838121843
I made a couple changes to the code in question that should hopefully resolve your problem.

**Comment by SpacedInvader** [comment]
The new dll appears to have corrected the issue, thanks for the quick reply.

**Comment by NathanKell** [comment]
Great!

**Comment by NathanKell** [comment]
@linuxgurugamer my guess is that one of those mods is doing hinky things with available parts, probably adding modules at runtime but with null ModuleInfos or something? At any rate, this fix checks for that and now everything should be fine.
