### ISSUE TITLE
Tank UI crashes [v15.8.2.0]

### ISSUE THREAD

**Issue by kretze** [KSP-RO/RealFuels#332]
Installed with CKAN, ROUtils is installed.

If I select an Avionics part that only has electric charge in it, the UI works.
![20231115185229_1](https://github.com/KSP-RO/RealFuels/assets/101901714/508bab10-761f-4b1c-9781-f8185edaf019)

If I select a tank and the entire propelant should be displayed, the UI crashes.
![20231115185214_1](https://github.com/KSP-RO/RealFuels/assets/101901714/3913e98a-a3e7-47df-b5fc-7c6987b640d6)

Tested with a new career and an older save.

Content from Log

[EXC 18:48:12.259] NullReferenceException: Object reference not set to an instance of an object
	RealFuels.Tanks.TankWindow.EnsureFreshAddLabelCache () (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	RealFuels.Tanks.TankWindow.GUITanks () (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	RealFuels.Tanks.TankWindow.GUIWindow (System.Int32 windowID) (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[ERR 18:48:12.259] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.

[EXC 18:48:12.274] NullReferenceException: Object reference not set to an instance of an object
	RealFuels.Tanks.TankWindow.EnsureFreshAddLabelCache () (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	RealFuels.Tanks.TankWindow.GUITanks () (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	RealFuels.Tanks.TankWindow.GUIWindow (System.Int32 windowID) (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[ERR 18:48:12.274] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.

[EXC 18:48:12.276] NullReferenceException: Object reference not set to an instance of an object
	RealFuels.Tanks.TankWindow.EnsureFreshAddLabelCache () (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	RealFuels.Tanks.TankWindow.GUITanks () (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	RealFuels.Tanks.TankWindow.GUIWindow (System.Int32 windowID) (at <f222fbd291fb4e54bc74af6a47cfdf9c>:0)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <58f888e0d56a4620958c8e58a768c70d>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[ERR 18:48:12.276] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.

**Comment by raghta** [comment]
I can confirm this as well, clean install with KSP 1.12.5 and Express Install on RP1, new game.  
We have had similar reports over discord already too

**Comment by NathanKell** [comment]
Fixed in https://github.com/KSP-RO/RealFuels/commit/11fc41a8388a1cbf72f1acd1bc5d8c94f8312821 and released v15.8.2.1
