### ISSUE TITLE
Cannot add fuel to procedural probe/avionics part

### ISSUE THREAD

**Issue by dennislee9999** [KSP-RO/RealFuels#333]
Hi, I am playing ksp with RP-1 express install on it.
About a month ago, I could add fuels to procedural probe or avionics part.
As it comes to my attention, I could not add fuels to these parts now.
Is this an intended updates, or am I missing something? I could not see any updates note regarding this phenomenon.

**Comment by lpgagnon** [comment]
https://github.com/KSP-RO/RP-1/releases/tag/v3.0.0.0
> Allow only EC to be added inside procedural avionics

**Comment by dennislee9999** [comment]
> https://github.com/KSP-RO/RP-1/releases/tag/v3.0.0.0
> 
> > Allow only EC to be added inside procedural avionics

Oh, I didn't catch up with that update note.
Thanks for the reply!
