### ISSUE TITLE
Problem detected with RefuelingPump

### ISSUE THREAD

**Issue by kretze** [KSP-RO/RealFuels#335]
Now that I'm using more powerful engines, I've noticed that the UmbilicalTower or 2 can't fill my tanks when the engines are started. Each UmbilicalTower is only filled with 100 l/s.

I did a search and came across RefuelingPump.cs. The pump_rate = 100 is permanently programmed there for the refueling tower.

I tested it in my current RP-1 game and then also a KSP blank installation with RealFuels + RO + KSPBurst.
In both installations I have the same effect.

This would also fit my research:
- ModuleManager Cache -> all RefuelingPump modules = 10000
`MODULE
{
	name = RefuelingPump
	pump_rate = 10000.0
}`
- in saved ships the RefuelingPump pump_rate = 100
`MODULE
{
	name = RefuelingPump
	isEnabled = True
	enablePump = True
	pump_rate = 100
	stagingEnabled = True
}`
- In the game, all UmbilicalTowers or launch stands only work at 100 l/s

According to my current understanding, the RefuelingPump values ​​of the parts are not read/used.

**Comment by Capkirk123** [comment]
This is probably intended behavior, the clamp pumps should only compensate for boiloff and other losses, they aren't expected to keep up with the fuel consumption of an engine for an extended period of time.

**Comment by kretze** [comment]
It's normal for the tanks to be filled until the nozzles are disconnected, so that the tanks are full to the brim when the lift-off occurs. This cannot currently be recreated.

**Comment by Capkirk123** [comment]
Do you have a source for that?

And those patches should probably not exist.

**Comment by kretze** [comment]
RealFuels/zLaunchClamps.cfg

**Comment by NathanKell** [comment]
In all situations I've heard of, feed lines are disconnected as part of startup--you don't want to be pumping propellants into a tank that's feeding a live engine. Most propellant utilization documents I've read explicitly refer to 'starting losses' or 'spoolup losses' to account for the propellant "wasted" between the time of line disconnect/engine start, and the time of liftoff.

**Comment by lpgagnon** [comment]
as for those patches not "working", fairly sure ROKerbalism's pump processes (visible as "Resource Pump" in those screenshots) supersede stock pumping?

**Comment by kretze** [comment]
Okay, actually it doesn't matter how you implement the whole thing. I only noticed it because the part info didn't match the actual values ​​applied.

Whether it is 100 or 10,000 will be correct. Then only both places should work with the same values ​​and be adjusted so that it fits again.

**Comment by kretze** [comment]
I just tested it.
If I adjust the zLaunchClamps.cfg and set it to 100, the pumps continue to work at 100 and the part info matches again.

**Comment by kretze** [comment]
I've now made myself a little smarter.
The Americans seem to switch off the refueling process about 2 minutes before lift-off. For the Ariane 5 it is probably 4:30 before.

Then it seems to have been a misunderstanding on my part. Too much information that had been picked up over time and was misinterpreted.

**Comment by Capkirk123** [comment]
TestFlight gives you a 5 second grace period on burn time for that exact reason, so you are not penalized for sitting on the pad to make sure your engines have all started.
